### ISSUE TITLE
Could not fetch Last.fm RSS feed

### ISSUE THREAD

**Issue by prietus** [weechat/scripts#97]
hi. since the lastfm upgrades on their site I always get Could not fetch Last.fm RSS feed when calling lastf.py. I cannot see any reference at all on the issues tracker so Im afraid im missing something. If I do, my apologies, if not heres the issue I get.

regards.

**Comment by timss** [comment]
The current [lastfm.py][1] relies on the now removed audioscrobbler 1.0 API. It needs an update in order to work with the 2.0 API:

- API authentication using an API key
- The API call for [recently played tracks][2] is changed
- Even though the  says it supports RSS it does not seem to be the case (tested). 

I suggest the script to be rewritten, but with the same interface and commands for the user. I'd be happy to do it, what do you think @flashcode ?

[1]: https://github.com/weechat/scripts/blob/master/python/lastfm.py
[2]: http://www.last.fm/api/show/user.getRecentTracks

**Comment by timss** [comment]
My bad for not checking the pending scripts section, appearantly I wasn't the first to pick this up after Last.fm started giving out API keys again.

https://weechat.org/scripts/pending/

Anyway, I went ahead and created yet another one from scratch. Reviewers might want to look at the comment field as to why (missing API keys, 3rd party libs, blocking requests, ..). 

Thanks.

**Comment by flashcode** [comment]
If the current lastfm script does not work at all any more, I would suggest updating or replacing it, not adding another new script with "2" as suffix, which would be confusing for users.

**Comment by timss** [comment]
Fair enough. Since it's a rewrite, it might make the most sense to replace it. In that case, how do you suggest it should be done? Update it using /scripts/update/, or maybe a pull request?

Either way, I would have to update the script accordingly, so the one pending would have to be replaced/discarded (it also has a typo which I'll fix).

**Comment by flashcode** [comment]
Then I can rename your script to "lastfm.py" when it will be accepted.
But there are 2 other pending scripts for lastfm, I have to check them too, to find differences.

**Comment by timss** [comment]
All righty. 

Here's a patch to update the currently pending lastfm2.py. 

    16c16
    < SCRIPT_NAME = 'lastfm2'
    ---
    > SCRIPT_NAME = 'lastfm'
    69c69
    <         'timeout': 10000
    ---
    >         'timeout': '10000'
    89,90c89,90
    <             artist = data['recenttracks']['track'][0]['artist']['#text']
    <             name = data['recenttracks']['track'][0]['name']
    ---
    >             artist = data['recenttracks']['track'][0]['artist']['#text'].encode('utf-8')
    >             name = data['recenttracks']['track'][0]['name'].encode('utf-8')
    102d101
    <

**Comment by flashcode** [comment]
@timss : there was a recent update on existing script lastfm.py (version 0.6), which is now using the working API.

**Comment by timss** [comment]
That's nice, thanks for the update. It still has a couple of drawbacks though:

- Does not support unicode, getting the very typical `UnicodeEncodeError`. 
- Only fetches based on configuration (`plugins.var.python...`), not argument using e.g. `/lastfm anotherusername`.

Of course, these and more could be added to the existing lastfm.py as well, although mine already has these and a few others incorporated already.

**Comment by timss** [comment]
I believe this may be closed.
